# Generated by Django 4.2.3 on 2023-07-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_like_posts_like_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='followersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('following', models.CharField(max_length=100)),
            ],
        ),
    ]
