# Generated by Django 4.2.3 on 2023-07-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='following',
            new_name='user',
        ),
    ]
