# Generated by Django 4.2.3 on 2023-07-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_post',
            name='comment',
            field=models.TextField(),
        ),
    ]
