# Generated by Django 4.2.3 on 2023-07-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_comment_post_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment_post',
        ),
    ]
