# Generated by Django 4.2.3 on 2023-07-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='publish',
        ),
    ]
